; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

; Vitesse du port série pour le débug
monitor_speed = 115200

; Partitionnement pour réserver de la place à LittleFS (Web Server)
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv

; Dépendances de bibliothèques
lib_deps =
       https://github.com/bblanchon/ArduinoJson.git
       https://github.com/ESP32Async/AsyncTCP.git
       https://github.com/ESP32Async/ESPAsyncWebServer.git

; --- Environnement de test local sur PC ---
[env:native]
platform = native
test_framework = unity
# Empêche la compilation de main.cpp et web_server lors du test natif
build_src_filter = +<*> -<main.cpp> -<web_server.cpp>
# Si vous utilisez un mock pour Arduino :
build_flags = 
    -D UNIT_TEST
    -I test/  # ou le dossier contenant votre mock Arduino
    -std=c++17
lib_deps = 
       https://github.com/bblanchon/ArduinoJson.git